import {AudioLines, LifeBuoy, Network, ShieldCheck} from 'lucide-react';

export const solutions=[
 {n:'01',slug:'conectividad',title:'Conectividad',copy:'Redes cableadas y WiFi estables, diseñadas para crecer contigo.',icon:Network,detail:'Creamos la infraestructura que mantiene cada dispositivo conectado con velocidad y estabilidad.',intro:'Una red debe desaparecer en el uso diario: rápida, estable y preparada para crecer sin convertirse en un problema.',items:['WiFi residencial y empresarial','Cableado estructurado y fibra óptica','Racks, switches y respaldo eléctrico','Diagnóstico y optimización de cobertura'],problems:['Zonas sin cobertura o señal inestable','Equipos desconectados en momentos críticos','Infraestructura sin orden ni documentación','Crecimiento limitado por una red improvisada'],spaces:['Residencias conectadas','Oficinas y corporativos','Hoteles y espacios comerciales'],result:'Una infraestructura documentada, estable y sencilla de administrar.'},
 {n:'02',slug:'seguridad',title:'Seguridad',copy:'Videovigilancia y control de acceso integrados, sin complicaciones.',icon:ShieldCheck,detail:'Protegemos personas y espacios con sistemas discretos que puedes consultar y controlar desde cualquier lugar.',intro:'La seguridad funciona mejor cuando protege sin invadir. Integramos visibilidad, acceso y alertas en una experiencia clara.',items:['Videovigilancia CCTV','Control de acceso','Interfonía y videoporteros','Alarmas, sensores e integración móvil'],problems:['Puntos ciegos y grabaciones poco útiles','Accesos sin registro o control central','Sistemas aislados difíciles de operar','Alertas que llegan tarde o no llegan'],spaces:['Residencias y condominios','Corporativos y comercios','Hospitalidad y áreas comunes'],result:'Control y evidencia disponibles cuando realmente los necesitas.'},
 {n:'03',slug:'experiencias',title:'Experiencias',copy:'Audio, video y automatización que se sienten naturales en cada espacio.',icon:AudioLines,detail:'Integramos entretenimiento, comunicación y automatización en una experiencia sencilla de operar.',intro:'La tecnología del espacio debe responder con naturalidad. Unimos imagen, sonido, iluminación y control en una sola experiencia.',items:['Audio distribuido','Salas de juntas y videoconferencia','Pantallas y señalización digital','Automatización e iluminación'],problems:['Controles distintos para cada sistema','Audio irregular o difícil de ajustar','Reuniones que comienzan con fallas técnicas','Automatizaciones que nadie sabe utilizar'],spaces:['Residencias premium','Salas de juntas','Hoteles, restaurantes y comercios'],result:'Espacios intuitivos que responden con uno o dos gestos.'},
 {n:'04',slug:'soporte',title:'Soporte',copy:'Acompañamiento continuo para que la tecnología nunca interrumpa tu operación.',icon:LifeBuoy,detail:'Cuidamos tu inversión después de la instalación y adaptamos el sistema conforme cambian tus necesidades.',intro:'Una buena instalación es el inicio. El soporte mantiene el sistema saludable, actualizado y listo para responder.',items:['Monitoreo y asistencia remota','Mantenimiento preventivo','Atención de incidencias','Actualización y crecimiento del sistema'],problems:['Fallas repetitivas sin causa identificada','Mantenimiento únicamente cuando algo deja de funcionar','Equipos desactualizados o sin respaldo','Dependencia de múltiples proveedores'],spaces:['Residencias administradas','Empresas con operación continua','Hoteles y propiedades multisistema'],result:'Continuidad operativa con un responsable que conoce tu instalación.'},
];

export type Solution=(typeof solutions)[number];
